use reactive::{SignalGet, SignalUpdate};
use taffy::prelude::TaffyMaxContent;

pub mod animation;
pub mod dynamic;
pub mod element;
pub mod event;
pub mod fragment;
pub mod image;
pub mod input;
pub mod resource;
pub mod root;
pub mod runtime;
pub mod sdl;
pub mod style;
pub mod text;
pub mod view;
pub mod view_id;
pub mod view_state;
pub mod view_tuple;

pub use crate::dynamic::{dynamic, lazy};
pub use crate::element::{Element, IntoElement};
pub use crate::event::Interactive;
pub use crate::fragment::{fragment, Fragment};
pub use crate::image::Image;
pub use crate::input::*;
pub use crate::resource::use_resource;
pub use crate::root::Root;
pub use crate::sdl::*;
pub use crate::text::{text, Text};
pub use crate::view::view;
pub use crate::view::View;
pub use crate::view_id::ViewId;
pub use peniko;
pub use reactive;
pub use sdl::ImageTexture;
pub use taffy;
