[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
image = "0.25.2"
wz_reader = { path = "../wz-reader-rs" }
ui = { path = "../ui" }
indexmap = "2.3.0"
thiserror = "1.0.57"
slotmap = "1.0.7"
tokio = { version = "1", features = ["full"] }
sdl3-sys = { version = "0.4.6", features = ["build-from-source-static"] }
hecs = "0.10.5"
log = "0.4.22"
symphonia = { version = "0.5.4", features = ["mp3"], default-features = false }
