[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
wz-parser = { path = "../wz-parser", default-features = false}
wz-splitter = { path = "../wz-splitter" }
ui = { path = "../ui" }
web-fetch = { path = "../web-fetch" }
async-runtime = { path = "../async-runtime" }
indexmap = "2.3.0"
thiserror = "1.0.57"
slotmap = "1.0.7"
sdl3-sys = { version = "0.4.6" }
hecs = "0.10.5"
log = "0.4.22"
symphonia = { version = "0.5.4", features = ["mp3"], default-features = false }
strum = { version = "0.27", features = ["derive"] }
image = { version = "0.25.2", default-features = false, features = ["png"] }
futures = "0.3"