[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
image = { version = "0.25.2", default-features = false, features = ["png", "jpeg"] }
wz-parser = { path = "../wz-parser", features = ["json", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
font-kit = "0.14.2"
clipboard-rs = "0.1.11"
rodio = "0.20.1"